# Generated by Django 4.0.1 on 2022-02-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_alter_course_name_alter_lecture_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='high_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.CharField(default='', help_text='Enter Image URL within 200 characters.', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='one_line_description',
            field=models.CharField(blank=True, default='', help_text='Describe the course in one but unforgettable line. Max 300 characters', max_length=300),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='one_line_description',
            field=models.CharField(blank=True, default='', help_text='Describe the lecture in one but unforgettable line. Max 300 characters', max_length=300),
        ),
    ]
