# Generated by Django 4.0.1 on 2022-02-12 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseapp', '0004_course_high_price_course_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('discount_percentage', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=100)),
                ('val', models.FloatField(blank=True, help_text='Do NOT change this field. It gets updated automatically.')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, unique=True)),
                ('high_price', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('image1', models.TextField(default='', max_length=200)),
                ('image2', models.TextField(default='', max_length=200)),
                ('image3', models.TextField(default='', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Leave this parameter empty, it will get generated automatically.')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('landmark', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Details',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.TextField(help_text="Customer's Orders")),
                ('total_cost', models.IntegerField(default=0)),
                ('code_applied', models.CharField(default='', max_length=20)),
                ('discounted_cost', models.IntegerField(default=0)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('address1', models.CharField(default='', max_length=100)),
                ('address2', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('pincode', models.CharField(default='', max_length=50)),
                ('landmark', models.CharField(default='', max_length=50)),
                ('ordered_at', models.DateTimeField(auto_now_add=True, help_text='Do NOT change this date and time field.')),
                ('last_changed_at', models.DateTimeField(auto_now=True, help_text='Do NOT change this date and time field.')),
                ('status', models.CharField(choices=[('OPS', 'Order Placed Successfully'), ('S', 'Shipped'), ('OFD', 'Out For Delivery'), ('D', 'Delivered')], default='Order Placed Successfully', help_text='Change this only when you are sure. This sends an email to the user regarding the update.', max_length=5)),
                ('user', models.ForeignKey(help_text='User who placed this order.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
