# Generated by Django 4.0.1 on 2022-02-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_coupon_product_userdetails_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Write the title within 200 characters.', max_length=256)),
                ('body', models.TextField(help_text='Your main content goes here.')),
                ('views', models.IntegerField(default=0, help_text='This statistic is for your reference, do not change it.')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('privacy', models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public')], default='PRIVATE', help_text='Public posts will appear to everyone and private posts only to you. Change this to private instead of deleting a post.', max_length=10)),
                ('slug', models.SlugField(blank=True, help_text='Leave this parameter empty, it will get generated automatically.')),
            ],
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='user',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
