# Generated by Django 4.0.1 on 2022-02-13 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0006_post_remove_coupon_name_remove_userdetails_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='BlogPost',
        ),
    ]
