# Generated by Django 4.0.1 on 2022-02-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0008_blogpost_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(default='This is my sample small description for a product.', help_text='Write a brief description of the product here.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='This area holds the HTML to show on the product page.'),
        ),
    ]
